name: ruby/setup-ruby

on: [push]

jobs:
  build:
    name: >-
      ${{ matrix.ruby }} ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-16.04, macos-latest, windows-latest ]
        ruby: [ ruby-head, 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, jruby, truffleruby ]
        exclude:
          - os:   windows-latest
            ruby: truffleruby
          
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ruby Install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Ruby Info
        run:  ruby ruby_info.rb
